app/assets/stylesheets/application.scss, app/assets/stylesheets/credits/credit.scss, app/assets/stylesheets/credits/credit_create.scss, app/views/credits/credit.html.haml, app/views/credits/credit_create.html.haml
=> credit views

app/assets/stylesheets/application.scss, app/assets/stylesheets/my_page_template.scss, app/assets/stylesheets/mypage_profile.scss, app/assets/stylesheets/newuser/newuser1.scss, app/assets/stylesheets/products/others_of_category.scss, app/assets/stylesheets/products/others_of_user.scss, app/assets/stylesheets/reset.scss, app/assets/stylesheets/sign_up.scss, app/assets/stylesheets/tests.scss, app/controllers/tests_controller.rb, app/views/products/_product.html.haml, app/views/products/index.html.haml, app/views/shared/_header.html.haml, app/views/shared/_main_footer.html.haml, app/views/tests/credit.html.haml, app/views/tests/credit_create.html.haml, app/views/tests/mypage_profile.html.haml, app/views/tests/newuser1.html.haml, config/routes.rb
=> 不要なコメントなどの削除

app/assets/stylesheets/my_page_template.scss, app/controllers/tests_controller.rb, app/views/tests/credit.html.haml, app/views/tests/newuser2.html.haml, app/views/tests/newuser3.html.haml, config/routes.rb
=> new user page3つ

app/assets/stylesheets/my_page_index.scss, app/views/tests/my_page_index.html.haml
=> (WIP)マイページトップ画面のマークアップ

app/views/tests/mypage_personal_information.html.haml
=> マイページ/本人情報登録画面の作成

app/controllers/application_controller.rb, app/views/devise/registrations/new.html.haml, app/views/tests/credit.html.haml, db/migrate/20191008122544_add_column_to_users.rb, db/schema.rb
=> user sanitize

app/assets/stylesheets/credits/credit.scss, app/assets/stylesheets/credits/credit_create.scss, app/controllers/signup_controller.rb, app/helpers/signup_helper.rb, app/views/shared/_header.html.haml, app/views/signup/done.html.haml, app/views/signup/step1.html.haml, app/views/signup/step2.html.haml, app/views/signup/step3.html.haml, app/views/signup/step4.html.haml, config/routes.rb
=> install completed

README.md, app/models/product.rb, app/views/layouts/application.html.haml, db/migrate/20191014115751_create_products.rb
=> product_sell

app/assets/stylesheets/application.scss, app/assets/stylesheets/products/edit.scss, app/controllers/products_controller.rb, app/views/products/edit.html.haml, config/routes.rb
=> products-edit

app/assets/javascripts/sell_form.js, app/controllers/products_controller.rb, app/views/products/category_children.json.jbuilder, app/views/products/category_grandchildren.json.jbuilder, app/views/products/new.html.haml, config/routes.rb
商品出品ページで商品のカテゴリーをjson形式で選択できるようにしました。
=> カテゴリー機能の実装

app/controllers/products_controller.rb, app/views/products/_product.html.haml, app/views/products/index.html.haml
zipで別々の変数を利用することもできますが、includesでまとめられました
.includes(:product_images)を利用
=> n+1問題の対策をしました

app/controllers/products_controller.rb, app/views/products/index.html.haml
トップページにカテゴリ別で商品を表示できるよう実装しました。
=> edit-product-index

app/assets/stylesheets/application.scss, app/controllers/products_controller.rb, app/views/products/edit.html.haml, config/routes.rb
出品ページと同様に作成。
.siblingsを使用して変更できるようにしました。
=> editページ実装しました

app/assets/javascripts/product.js, app/assets/javascripts/sell_form.js, app/assets/stylesheets/index.scss, app/assets/stylesheets/products/confirmation.scss, app/assets/stylesheets/products/header.scss, app/views/products/_product.html.haml, app/views/products/edit.html.haml, app/views/products/mine.html.haml
* 相対パスから絶対パスに変更することでeditからもnewからも通信できるようにした。
=> 商品編集ページの詳細を変更

app/controllers/products_controller.rb, app/models/product.rb, app/models/purchase.rb, app/models/user.rb, db/migrate/20191020083623_create_purchases.rb, db/schema.rb
=> productとuserの中間テーブル作成しました。

app/assets/stylesheets/logout.scss, app/controllers/products_controller.rb, db/migrate/20191020094852_add_status_column_to_products.rb, db/schema.rb
pay action内でupdate_attributesを用いてstatusカラムを書き換える処理を記述
where(status: '出品中')を用いてindexpageでは出品中のもののみを表示するようにした
=> Create status column

app/assets/stylesheets/application.scss, app/assets/stylesheets/sold_triangle.scss, app/views/products/_product.html.haml
商品が入れたら(statusが"取引中"になったら)商品画像の左上にSOLDボタンを出すようにしました。
=> SOLDボタンの追加

app/assets/stylesheets/products/links_under_product.scss, app/controllers/application_controller.rb, app/controllers/signup_controller.rb, app/models/product.rb, app/views/layouts/application.html.haml, app/views/products/_links_under_product.html.haml, app/views/signup/step3.html.haml, app/views/users/newuser3.html.haml, db/migrate/20191021032509_address_to_users.rb, db/migrate/20191021032849_housenumber_to_users.rb, db/schema.rb
ユーザー住所の登録機能実装
郵便番号から住所を自動登録できるようにした
=> Update user signup

app/assets/javascripts/product.js, app/assets/javascripts/sell_form.js, app/assets/stylesheets/products/product.scss, app/views/products/_product.html.haml
- jsで mouseenter時に画像を差し替える機能を実装
- 上に表示されている画像と同じiconのものはopacityを1 その他はopacity を0.4にした
=> Image icon hover

app/assets/stylesheets/application.scss, app/assets/stylesheets/my_page_index.scss, app/assets/stylesheets/stop_listing.scss, app/controllers/users_controller.rb, app/views/products/_product.html.haml, app/views/users/_mines.html.haml
出品した商品 ページのステータスの変更
出品中一覧には
「出品中」と「公開停止中」を表示
「出品中」は赤色背景、「公開停止中」は青色背景
出品中一覧
「取引中」は赤色背景
売却済み一覧
「売却済み」グレー背景
=> 商品ステータスの変更

app/views/signup/step4.html.haml
=> ユーザー新規登録画面の修正

app/assets/stylesheets/complete.scss
=> 購入完了ページの修正

app/assets/stylesheets/sell_form.scss, app/views/products/new.html.haml
1.出品画面にヘッダーを追加
→メルカリロゴ
2.jQueryを使用してもどるボタンの実装
→クラス名.{ onclick : " window.history.back () ; " }.表示する文字
1個前のページにもどる
=> 出品画面のアップデート

app/controllers/products_controller.rb, app/controllers/users_controller.rb, app/models/product.rb, app/views/products/_product.html.haml, app/views/products/mine.html.haml, app/views/users/_mines.html.haml, config/routes.rb, db/migrate/20191020094852_add_status_column_to_products.rb, db/migrate/20191025121547_add_column_to_product.rb, db/schema.rb, spec/factories/product.rb
商品詳細画面から商品の出品状態（公開停止、出品再開）を変更できるようにした。
=> 商品出品停止状態の追加

app/assets/javascripts/edit_validation.js, app/assets/stylesheets/sell_form.scss, app/controllers/products_controller.rb, app/views/products/edit.html.haml
#edit 機能の修正。
edit-buttonというクラスを新しく追加したことで解決しました。
=> editできるようにしました
